FROM debian:bullseye-slim

ARG TARGETARCH

LABEL maintainer="Richard Kojedzinszky <richard@kojedz.in>"

RUN apt-get update && \
    apt-get install -y reprepro && \
    rm -rf /var/lib/apt /var/cache/apt

RUN groupadd -g 29295 reprepro && \
    useradd -g reprepro -u 29295 -c "Reprepro User" -s /bin/sh \
    -d /home/reprepro -M reprepro

COPY assets-server /

COPY server.${TARGETARCH} /usr/local/bin/server

EXPOSE 8080

USER 29295

CMD ["/usr/local/bin/server"]
